<?php
/** @var Index $block */
use Gundo\Imagine\Block\Index;
?>
<div class="imagine-form">
    <form action="<?= $block->escapeUrl($block->getFormAction()); ?>" method="POST">
        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()); ?>"/>

        <div class="field required">
            <label for="name" class="label"><span><?= __('Generate T-Shirt From Prompt'); ?></span></label>
            <div class="control">
                <input name="prompt" id="prompt"
                       title="<?= __('Generate Image with Any text e.g CyberPunk Sahara'); ?>"
                       value="<?= $block->escapeHtml($block->getFormData('prompt')); ?>" class="input-text"
                       type="text" data-validate="{required:true}">
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action primary" title="<?= __('Generate Design'); ?>">
                    <span><?= __('Generate'); ?></span>
                </button>
            </div>
        </div>
        <?= $block->getChildHtml('form.additional.info.imagine') ?>
    </form>
</div>
