<?php declare(strict_types=1);

namespace Gundo\Imagine\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Magento\Framework\App\ResourceConnection;

class CleanUp extends Command
{
    /**
     * @var ResourceConnection
     */
    private ResourceConnection $resourceConnection;

    /**
     * @param ResourceConnection $resourceConnection
     */
    public function __construct(ResourceConnection $resourceConnection)
    {
        $this->resourceConnection = $resourceConnection;
        parent::__construct();
    }

    /**
     * Initialization of the command.
     */
    protected function configure(): void
    {
        $this->setName('imagine:cleanup');
        $this->setDescription('Clean Up old images from autogenerated products.');
        parent::configure();
    }

    /**
     * CLI command description.
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     * @throws \Exception
     */
    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $connection = $this->resourceConnection->getConnection();
        $tableName = $connection->getTableName('imagine');

        $date = new \DateTime('now');
//        $date->sub(new \DateInterval('P30D'));
        //30 seconds for testing
        $date->sub(new \DateInterval('PT30S'));
        $formattedDate = $date->format('Y-m-d H:i:s');
        $output->writeln('Deleting records older than: ' . $formattedDate);
        $output->writeln('Before deleting records...');

        $sql = "DELETE FROM $tableName WHERE created_at < :date";
        $binds = ['date' => $formattedDate];
       $output->writeln('SQL: ' . $sql);

        $connection->query($sql, $binds);
        $output->writeln('Affected: ' . $connection->fetchOne("SELECT ROW_COUNT()"));
        $output->writeln('Old records have been deleted.');
        return 0;
    }
}
